name: AetherLabsPlugin
version: '${project.version}'
main: com.loficostudios.minigameeventsplugin.AetherLabsPlugin
api-version: '1.21'
softdepend: [PlaceholderAPI]
author: tonierbobcat
website: www.loficostudios.com