name: MiniGamePlugin
version: '${project.version}'
main: com.loficostudios.minigameeventsplugin.RandomEventsPlugin
api-version: '1.21'
depend: [MelodyAPI]
softdepend: [Essentials, PlaceholderAPI, Vault]